### ISSUE TITLE
Mines: option to swap tap / tap-and-hold actions

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#240]
Dirmansyah Lubis asks for tap to flag and long press to dig.

**Comment by chrisboyle** [comment]
Mandy Zhou reports that Mines "doesn't consistently recognise long presses", which this option might also help with.

**Comment by chrisboyle** [comment]
This is effectively a duplicate of #25, in that a persistent-state keyboard button which swaps left and right click would solve it.

**Comment by chrisboyle** [comment]
I implemented that in 2b5c404; will be in the next update. :-)

**Comment by TPS** [comment]
Reading through https://github.com/chrisboyle/sgtpuzzles/commit/2b5c404ba401e52aa6e0ccc8018da23bdb5c2acd, https://github.com/chrisboyle/sgtpuzzles/issues/25, & this issue, I still don't quite understand how to do this.…

**Comment by TPS** [comment]
~~Reading through https://github.com/chrisboyle/sgtpuzzles/commit/2b5c404ba401e52aa6e0ccc8018da23bdb5c2acd, https://github.com/chrisboyle/sgtpuzzles/issues/25, & this issue, I still don't quite understand how to do this.…~~

Nevermind, I figured it out, but more clearly labeled buttons would be helpful!  I had no idea what that weird icon meant!
